import type { AfsDisclosureDefault } from "./afsDisclosureTypes";

export const AFS_DISCLOSURE_DEFAULTS: AfsDisclosureDefault[] = [
  // COVER
  {
    pageKey: "cover",
    sectionKey: "cover",
    disclosureKey: "client-logo",
    title: "Client logo",
    defaultEnabled: false,
    defaultOrder: 10,
    source: "manual",
    hideIfBlank: true,
  },
  {
    pageKey: "cover",
    sectionKey: "cover",
    disclosureKey: "framework-line",
    title: "Framework line",
    defaultEnabled: false,
    defaultOrder: 20,
    source: "client-setup",
    defaultText: "These financial statements were prepared in terms of {{basis_of_preparation}}.",
    allowCustomText: true,
  },
  {
    pageKey: "cover",
    sectionKey: "cover",
    disclosureKey: "no-assurance-line",
    title: "No audit/review line",
    defaultEnabled: false,
    defaultOrder: 30,
    source: "client-setup",
    defaultText: "These financial statements have not been audited or independently reviewed.",
    allowCustomText: true,
  },

  // GENERAL INFORMATION
  {
    pageKey: "general-information",
    sectionKey: "general-information",
    disclosureKey: "company-name",
    title: "Company name",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "client-setup",
    hideIfBlank: true,
  },
  {
    pageKey: "general-information",
    sectionKey: "general-information",
    disclosureKey: "registration-number",
    title: "Registration number",
    defaultEnabled: true,
    defaultOrder: 20,
    source: "client-setup",
    hideIfBlank: true,
  },
  {
    pageKey: "general-information",
    sectionKey: "general-information",
    disclosureKey: "directors-members-trustees",
    title: "Directors / members / trustees",
    defaultEnabled: true,
    defaultOrder: 50,
    source: "people",
    hideIfBlank: true,
  },
  {
    pageKey: "general-information",
    sectionKey: "general-information",
    disclosureKey: "registered-office",
    title: "Registered office",
    defaultEnabled: true,
    defaultOrder: 60,
    source: "client-setup",
    hideIfBlank: true,
  },
  {
    pageKey: "general-information",
    sectionKey: "general-information",
    disclosureKey: "business-address",
    title: "Business address",
    defaultEnabled: true,
    defaultOrder: 70,
    source: "client-setup",
    hideIfBlank: true,
  },

  // DIRECTORS RESPONSIBILITIES
  {
    pageKey: "directors-responsibilities",
    sectionKey: "responsibilities",
    disclosureKey: "responsibilities-main",
    title: "Main responsibilities wording",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "static",
    allowCustomText: true,
  },
  {
    pageKey: "directors-responsibilities",
    sectionKey: "responsibilities",
    disclosureKey: "internal-control",
    title: "Internal control wording",
    defaultEnabled: true,
    defaultOrder: 20,
    source: "static",
    allowCustomText: true,
  },
  {
    pageKey: "directors-responsibilities",
    sectionKey: "responsibilities",
    disclosureKey: "going-concern-responsibilities",
    title: "Going concern wording",
    defaultEnabled: true,
    defaultOrder: 30,
    source: "client-setup",
    allowCustomText: true,
    variants: [
      {
        key: "standard",
        label: "Standard going concern",
        text: "The {{director_label}} have assessed the company's ability to continue as a going concern and are satisfied that the company has adequate resources to continue in operational existence for the foreseeable future."
      },
      {
        key: "not-going-concern",
        label: "Not prepared on going concern basis",
        text: "The annual financial statements have not been prepared on a going concern basis."
      },
      {
        key: "material-uncertainty",
        label: "Material uncertainty",
        text: "Certain conditions have given rise to a material uncertainty which may cast significant doubt about the company's ability to continue as a going concern."
      }
    ],
  },

  // DIRECTORS REPORT
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "incorporation-review",
    title: "Incorporation / nature / review of activities",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "client-setup",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "financial-results",
    title: "Financial results",
    defaultEnabled: true,
    defaultOrder: 20,
    source: "static",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "events-after-reporting-date",
    title: "Events after reporting date",
    defaultEnabled: true,
    defaultOrder: 30,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "director-interest-contracts",
    title: "Director's interest in contracts",
    defaultEnabled: false,
    defaultOrder: 40,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "authorised-issued-share-capital",
    title: "Authorised and issued share capital",
    defaultEnabled: true,
    defaultOrder: 50,
    source: "client-setup",
    allowCustomText: true,
    allowManualValue: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "borrowing-limitations",
    title: "Borrowing limitations",
    defaultEnabled: false,
    defaultOrder: 60,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "dividends",
    title: "Dividends",
    defaultEnabled: true,
    defaultOrder: 70,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "directors",
    title: "Directors / members / trustees",
    defaultEnabled: true,
    defaultOrder: 80,
    source: "people",
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "social-ethics-committee",
    title: "Social and ethics committee",
    defaultEnabled: false,
    defaultOrder: 90,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "secretary",
    title: "Secretary",
    defaultEnabled: true,
    defaultOrder: 100,
    source: "client-setup",
    allowCustomText: true,
    hideIfBlank: false,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "shareholder",
    title: "Shareholder / ownership interest",
    defaultEnabled: false,
    defaultOrder: 110,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "subsidiaries-associates-joint-ventures",
    title: "Subsidiaries / associates / joint ventures",
    defaultEnabled: false,
    defaultOrder: 120,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "ppe-additions",
    title: "Non-current assets / PPE additions",
    defaultEnabled: false,
    defaultOrder: 130,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "going-concern",
    title: "Going concern",
    defaultEnabled: true,
    defaultOrder: 140,
    source: "client-setup",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "liquidity-solvency",
    title: "Liquidity and solvency",
    defaultEnabled: true,
    defaultOrder: 150,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "litigation",
    title: "Litigation statement",
    defaultEnabled: true,
    defaultOrder: 160,
    source: "manual",
    allowCustomText: true,
  },
  {
    pageKey: "directors-report",
    sectionKey: "directors-report",
    disclosureKey: "external-accountant",
    title: "External accountant / compiler",
    defaultEnabled: true,
    defaultOrder: 170,
    source: "client-setup",
    allowCustomText: true,
  },

  // COMPILER REPORT
  {
    pageKey: "compiler-report",
    sectionKey: "compiler-report",
    disclosureKey: "letterhead",
    title: "Firm letterhead",
    defaultEnabled: true,
    defaultOrder: 5,
    source: "manual",
    hideIfBlank: true,
  },
  {
    pageKey: "compiler-report",
    sectionKey: "compiler-report",
    disclosureKey: "isrs4410-report",
    title: "ISRS 4410 compilation report wording",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "static",
    allowCustomText: true,
  },

  // STATEMENTS AND NOTES
  {
    pageKey: "statement-financial-position",
    sectionKey: "statement",
    disclosureKey: "sfp-lines",
    title: "Statement of financial position lines",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "trial-balance",
    allowNoteNumber: true,
  },
  {
    pageKey: "statement-profit-loss",
    sectionKey: "statement",
    disclosureKey: "spl-lines",
    title: "Statement of profit or loss lines",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "trial-balance",
    allowNoteNumber: true,
  },
  {
    pageKey: "statement-changes-equity",
    sectionKey: "statement",
    disclosureKey: "socie-lines",
    title: "Statement of changes in equity",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "computed",
  },
  {
    pageKey: "cash-flow",
    sectionKey: "statement",
    disclosureKey: "cash-flow-lines",
    title: "Statement of cash flows",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "computed",
  },
  {
    pageKey: "accounting-policies",
    sectionKey: "policies",
    disclosureKey: "basis-of-preparation",
    title: "Basis of preparation",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "client-setup",
    allowCustomText: true,
  },
  {
    pageKey: "notes",
    sectionKey: "notes",
    disclosureKey: "notes-register",
    title: "Notes to the annual financial statements",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "lead-schedule",
    allowCustomText: true,
    allowNoteNumber: true,
  },
  {
    pageKey: "detailed-income-statement",
    sectionKey: "statement",
    disclosureKey: "detailed-income-lines",
    title: "Detailed income statement",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "trial-balance",
  },
  {
    pageKey: "tax-computation",
    sectionKey: "tax",
    disclosureKey: "tax-computation-lines",
    title: "Tax computation",
    defaultEnabled: true,
    defaultOrder: 10,
    source: "computed",
  },
];
