export type AfsDisclosureType = "note" | "policy";

export type AfsDisclosureStatementArea =
  | "sfp"
  | "soci"
  | "sce"
  | "cash-flow"
  | "other";

export type AfsDisclosureLibraryItem = {
  key: string;
  title: string;
  type: AfsDisclosureType;
  statementArea: AfsDisclosureStatementArea;
  defaultEnabled: boolean;
  displayOrder: number;
  isCore?: boolean;
  supportsSplit?: boolean;
  supportsTerms?: boolean;
  supportsMovementMatrix?: boolean;
  linkedMappingPrefixes?: string[];
  policyKey?: string;
  defaultText?: string;
};

export const AFS_DISCLOSURE_LIBRARY: AfsDisclosureLibraryItem[] = [
  {
    key: "property-plant-equipment",
    title: "Property, plant and equipment",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 10,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["305", "306"],
    policyKey: "property-plant-equipment",
    defaultText:
      "Property, plant and equipment are tangible assets held for use in the production or supply of goods or services, for rental to others, or for administrative purposes.",
  },
  {
    key: "right-of-use-assets",
    title: "Right-of-use assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 20,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["306"],
    policyKey: "leases",
    defaultText:
      "Right-of-use assets are disclosed by class of underlying asset and reconciled from opening to closing carrying amount where material.",
  },
  {
    key: "investment-property",
    title: "Investment property",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 30,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["310"],
    policyKey: "investment-property",
    defaultText:
      "Investment property comprises property held to earn rentals, for capital appreciation, or both.",
  },
  {
    key: "goodwill",
    title: "Goodwill",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 40,
    supportsTerms: true,
    linkedMappingPrefixes: ["321"],
    policyKey: "goodwill-and-impairment",
    defaultText:
      "Goodwill is tested for impairment annually and when indicators of impairment exist.",
  },
  {
    key: "intangible-assets",
    title: "Intangible assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 50,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["320", "326"],
    policyKey: "intangible-assets",
    defaultText:
      "Intangible assets are identifiable non-monetary assets without physical substance.",
  },
  {
    key: "biological-assets",
    title: "Biological assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 60,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["330"],
    policyKey: "biological-assets",
    defaultText:
      "Biological assets are measured and disclosed in accordance with the applicable accounting policy.",
  },
  {
    key: "investments-in-subsidiaries",
    title: "Investments in subsidiaries",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 70,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["326"],
    policyKey: "group-and-consolidation",
  },
  {
    key: "investments-in-associates",
    title: "Investments in associates",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 80,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["327"],
    policyKey: "group-and-consolidation",
  },
  {
    key: "investments-in-joint-ventures",
    title: "Investments in joint ventures",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 90,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["328"],
    policyKey: "group-and-consolidation",
  },
  {
    key: "other-financial-assets",
    title: "Other financial assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: true,
    displayOrder: 100,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["390", "395"],
    policyKey: "financial-instruments",
    defaultText:
      "Other financial assets are disclosed by class and measured in accordance with the entity's accounting policies for financial instruments.",
  },
  {
    key: "loans-receivable",
    title: "Loans receivable",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 110,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["340"],
    policyKey: "financial-instruments",
  },
  {
    key: "inventories",
    title: "Inventories",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: true,
    displayOrder: 120,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["410"],
    policyKey: "inventories",
    defaultText: "Inventories are analysed by category where applicable.",
  },
  {
    key: "trade-and-other-receivables",
    title: "Trade and other receivables",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 130,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["430"],
    policyKey: "cash-receivables-and-payables",
  },
  {
    key: "current-tax-receivable-payable",
    title: "Current tax receivable / payable",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 140,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["455", "610"],
    policyKey: "taxation",
  },
  {
    key: "cash-and-cash-equivalents",
    title: "Cash and cash equivalents",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: true,
    displayOrder: 150,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["420"],
    policyKey: "cash-receivables-and-payables",
    defaultText:
      "Cash and cash equivalents consist of cash on hand, bank balances and short-term deposits, net of bank overdrafts where applicable.",
  },
  {
    key: "share-capital",
    title: "Share capital",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: true,
    displayOrder: 160,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["810"],
    policyKey: "equity",
  },
  {
    key: "shareholders-loans",
    title: "Loans to / (from) shareholders",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: true,
    displayOrder: 170,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["548"],
    policyKey: "financial-instruments",
    defaultText:
      "Shareholder loans are disclosed with the main terms and conditions. Where no formal repayment terms exist, this should be disclosed.",
  },
  {
    key: "other-financial-liabilities",
    title: "Other financial liabilities",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 180,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["590", "500.590", "547", "531"],
    policyKey: "financial-instruments",
    defaultText:
      "Other financial liabilities are disclosed by lender, relationship, interest terms, repayment terms and security where applicable.",
  },
  {
    key: "trade-and-other-payables",
    title: "Trade and other payables",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 190,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["600"],
    policyKey: "cash-receivables-and-payables",
  },
  {
    key: "revenue",
    title: "Revenue",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 200,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["900"],
    policyKey: "revenue",
  },
  {
    key: "other-income",
    title: "Other income",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 210,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["910"],
    policyKey: "revenue",
  },
  {
    key: "operating-expenses",
    title: "Operating expenses",
    type: "note",
    statementArea: "soci",
    defaultEnabled: true,
    displayOrder: 220,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["960"],
    policyKey: "operating-expenses",
  },
  {
    key: "finance-costs",
    title: "Finance costs",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 230,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["970"],
    policyKey: "operating-expenses",
  },
  {
    key: "taxation",
    title: "Taxation",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 240,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["980", "610", "455"],
    policyKey: "taxation",
  },
  {
    key: "cash-used-in-operations",
    title: "Cash generated from / (used in) operations",
    type: "note",
    statementArea: "cash-flow",
    defaultEnabled: true,
    displayOrder: 250,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: [],
    policyKey: "cash-flow",
  },
];

export const AFS_ACCOUNTING_POLICY_LIBRARY: AfsDisclosureLibraryItem[] = [
  {
    key: "basis-of-preparation",
    title: "Basis of preparation",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 10,
    isCore: true,
  },
  {
    key: "statement-of-compliance",
    title: "Statement of compliance with IFRS",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 20,
    isCore: true,
  },
  {
    key: "going-concern",
    title: "Going concern",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 30,
    isCore: true,
  },
  {
    key: "material-accounting-policy-information",
    title: "Material accounting policy information",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 40,
    isCore: true,
  },
  {
    key: "financial-instruments",
    title: "Financial instruments",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 100,
  },
  {
    key: "cash-receivables-and-payables",
    title: "Cash, receivables and payables",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 110,
  },
  {
    key: "inventories",
    title: "Inventories",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 120,
  },
  {
    key: "property-plant-equipment",
    title: "Property, plant and equipment",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 130,
  },
  {
    key: "investment-property",
    title: "Investment property",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 140,
  },
  {
    key: "intangible-assets",
    title: "Intangible assets",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 150,
  },
  {
    key: "goodwill-and-impairment",
    title: "Goodwill and impairment",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 160,
  },
  {
    key: "leases",
    title: "Leases",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 170,
  },
  {
    key: "revenue",
    title: "Revenue",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 180,
  },
  {
    key: "operating-expenses",
    title: "Operating expenses",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 190,
  },
  {
    key: "taxation",
    title: "Taxation",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 200,
  },
  {
    key: "equity",
    title: "Equity",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 210,
  },
];

export function sortDisclosureLibrary<T extends { displayOrder: number; title: string }>(items: T[]) {
  return [...items].sort((a, b) => a.displayOrder - b.displayOrder || a.title.localeCompare(b.title));
}
