export type AfsDisclosureType = "note" | "policy";

export type AfsDisclosureStatementArea =
  | "sfp"
  | "soci"
  | "sce"
  | "cash-flow"
  | "other";

export type AfsDisclosureLibraryItem = {
  key: string;
  title: string;
  type: AfsDisclosureType;
  statementArea: AfsDisclosureStatementArea;
  defaultEnabled: boolean;
  displayOrder: number;
  isCore?: boolean;
  supportsSplit?: boolean;
  supportsTerms?: boolean;
  supportsMovementMatrix?: boolean;
  linkedMappingPrefixes?: string[];
  policyKey?: string;
  defaultText?: string;
};

export const AFS_DISCLOSURE_LIBRARY: AfsDisclosureLibraryItem[] = [
  // ---------------------------------------------------------------------------
  // STATEMENT OF FINANCIAL POSITION — ASSETS
  // ---------------------------------------------------------------------------
  {
    key: "property-plant-equipment",
    title: "Property, plant and equipment",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 10,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["305"],
    policyKey: "property-plant-equipment",
    defaultText:
      "Property, plant and equipment are disclosed by class with the applicable movement reconciliation and material commitments or security disclosures.",
  },
  {
    key: "right-of-use-assets",
    title: "Right-of-use assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 20,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["306"],
    policyKey: "leases",
    defaultText:
      "Right-of-use assets are disclosed by class of underlying asset where the selected reporting framework requires separate presentation.",
  },
  {
    key: "investment-property",
    title: "Investment property",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 30,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["310"],
    policyKey: "investment-property",
  },
  {
    key: "intangible-assets",
    title: "Intangible assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 40,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["320"],
    policyKey: "intangible-assets",
  },
  {
    key: "goodwill",
    title: "Goodwill",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 50,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["321"],
    policyKey: "goodwill-and-impairment",
  },
  {
    key: "investments-in-subsidiaries",
    title: "Investments in subsidiaries",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 60,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["326"],
    policyKey: "group-and-consolidation",
  },
  {
    key: "investments-in-associates",
    title: "Investments in associates",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 70,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["327"],
    policyKey: "group-and-consolidation",
  },
  {
    key: "investments-in-joint-ventures",
    title: "Investments in joint ventures",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 80,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["328"],
    policyKey: "group-and-consolidation",
  },
  {
    key: "other-investments",
    title: "Other investments",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 90,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["329"],
    policyKey: "financial-instruments",
  },
  {
    key: "biological-assets",
    title: "Biological assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 100,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["330", "410"],
    policyKey: "biological-assets",
  },
  {
    key: "loans-receivable",
    title: "Loans receivable",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 110,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["340", "449"],
    policyKey: "financial-instruments",
    defaultText:
      "Loans receivable are disclosed by counterparty and include material interest, repayment, security and related-party terms where applicable.",
  },
  {
    key: "other-financial-assets",
    title: "Other financial assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 120,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["350", "435"],
    policyKey: "financial-instruments",
  },
  {
    key: "other-non-current-assets",
    title: "Other non-current assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 130,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["390"],
    policyKey: "other-assets",
  },
  {
    key: "deferred-tax-asset",
    title: "Deferred tax asset",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 140,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["395"],
    policyKey: "taxation",
  },
  {
    key: "inventories",
    title: "Inventories",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 150,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["405"],
    policyKey: "inventories",
    defaultText: "Inventories are analysed by category where applicable.",
  },
  {
    key: "contract-assets",
    title: "Contract assets",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 160,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["415"],
    policyKey: "revenue",
  },
  {
    key: "cash-and-cash-equivalents",
    title: "Cash and cash equivalents",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 170,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["420"],
    policyKey: "cash-receivables-and-payables",
  },
  {
    key: "trade-and-other-receivables",
    title: "Trade and other receivables",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 180,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["430"],
    policyKey: "cash-receivables-and-payables",
  },
  {
    key: "tax-and-statutory-receivables",
    title: "Tax and statutory receivables",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 190,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["490"],
    policyKey: "taxation",
  },
  {
    key: "current-tax-receivable",
    title: "Current tax receivable",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 200,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["495"],
    policyKey: "taxation",
  },
  {
    key: "assets-held-for-sale",
    title: "Assets held for sale",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 210,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["499"],
    policyKey: "assets-held-for-sale",
  },

  // ---------------------------------------------------------------------------
  // STATEMENT OF FINANCIAL POSITION — EQUITY
  // ---------------------------------------------------------------------------
  {
    key: "share-capital",
    title: "Share capital / contributions",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 300,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["805"],
    policyKey: "equity",
  },
  {
    key: "retained-income",
    title: "Retained income / accumulated loss",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 310,
    supportsSplit: true,
    linkedMappingPrefixes: ["810"],
    policyKey: "equity",
  },
  {
    key: "reserves",
    title: "Reserves",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 320,
    supportsSplit: true,
    supportsMovementMatrix: true,
    linkedMappingPrefixes: ["820"],
    policyKey: "equity",
  },
  {
    key: "non-controlling-interests",
    title: "Non-controlling interests",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 330,
    supportsSplit: true,
    linkedMappingPrefixes: ["830"],
    policyKey: "group-and-consolidation",
  },
  {
    key: "other-equity",
    title: "Other equity",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 340,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["840"],
    policyKey: "equity",
  },

  // ---------------------------------------------------------------------------
  // STATEMENT OF FINANCIAL POSITION — LIABILITIES
  // ---------------------------------------------------------------------------
  {
    key: "provisions",
    title: "Provisions",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 400,
    supportsSplit: true,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["515", "660"],
    policyKey: "provisions",
  },
  {
    key: "employee-benefit-obligations",
    title: "Employee benefit obligations",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 410,
    supportsSplit: true,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["520", "670"],
    policyKey: "employee-benefits",
  },
  {
    key: "deferred-income-and-grants",
    title: "Deferred income and government grants",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 420,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["531", "650"],
    policyKey: "government-grants",
  },
  {
    key: "group-related-party-borrowings",
    title: "Group and related-party borrowings",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 430,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["547"],
    policyKey: "financial-instruments",
    defaultText:
      "Group and related-party borrowings are disclosed by lender and include material interest, repayment, security and related-party terms.",
  },
  {
    key: "shareholders-loans",
    title: "Shareholder / director / member loans",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 440,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["548"],
    policyKey: "financial-instruments",
  },
  {
    key: "borrowings",
    title: "Borrowings",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 450,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["550", "551", "610"],
    policyKey: "financial-instruments",
    defaultText:
      "Borrowings are analysed by material facility and disclose lender, interest, repayment, security, maturity and current/non-current portions where applicable.",
  },
  {
    key: "asset-finance",
    title: "Asset finance / instalment sale liabilities",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 460,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["550.40", "550.50", "610.30", "610.40"],
    policyKey: "financial-instruments",
  },
  {
    key: "lease-liabilities",
    title: "Lease liabilities",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 470,
    supportsSplit: true,
    supportsMovementMatrix: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["555", "615"],
    policyKey: "leases",
  },
  {
    key: "other-financial-liabilities",
    title: "Other financial liabilities",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 480,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["560", "625", "590"],
    policyKey: "financial-instruments",
  },
  {
    key: "supplier-finance-arrangements",
    title: "Supplier finance arrangements",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 490,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["580", "680"],
    policyKey: "financial-instruments",
  },
  {
    key: "deferred-tax-liability",
    title: "Deferred tax liability",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 500,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["595"],
    policyKey: "taxation",
  },
  {
    key: "bank-overdraft",
    title: "Bank overdraft",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 510,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["620"],
    policyKey: "financial-instruments",
  },
  {
    key: "trade-and-other-payables",
    title: "Trade and other payables",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 520,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["630"],
    policyKey: "cash-receivables-and-payables",
  },
  {
    key: "contract-liabilities",
    title: "Contract liabilities / deferred revenue",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 530,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["640"],
    policyKey: "revenue",
  },
  {
    key: "dividend-payable",
    title: "Dividend payable",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 540,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["688"],
    policyKey: "equity",
  },
  {
    key: "tax-and-statutory-payables",
    title: "Tax and statutory payables",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 550,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["690"],
    policyKey: "taxation",
  },
  {
    key: "current-tax-payable",
    title: "Current tax payable",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 560,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["695"],
    policyKey: "taxation",
  },
  {
    key: "liabilities-held-for-sale",
    title: "Liabilities held for sale",
    type: "note",
    statementArea: "sfp",
    defaultEnabled: false,
    displayOrder: 570,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["699"],
    policyKey: "assets-held-for-sale",
  },

  // ---------------------------------------------------------------------------
  // STATEMENT OF PROFIT OR LOSS / COMPREHENSIVE INCOME
  // ---------------------------------------------------------------------------
  {
    key: "revenue",
    title: "Revenue",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 600,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["700"],
    policyKey: "revenue",
  },
  {
    key: "cost-of-sales",
    title: "Cost of sales",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 610,
    supportsSplit: true,
    linkedMappingPrefixes: ["720"],
    policyKey: "inventories",
  },
  {
    key: "other-operating-income",
    title: "Other operating income",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 620,
    supportsSplit: true,
    linkedMappingPrefixes: ["730"],
    policyKey: "revenue",
  },
  {
    key: "investment-income",
    title: "Investment income",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 630,
    supportsSplit: true,
    linkedMappingPrefixes: ["770"],
    policyKey: "financial-instruments",
  },
  {
    key: "operating-expenses",
    title: "Operating expenses",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 640,
    supportsSplit: true,
    linkedMappingPrefixes: ["750"],
    policyKey: "operating-expenses",
  },
  {
    key: "finance-costs",
    title: "Finance costs",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 650,
    supportsSplit: true,
    linkedMappingPrefixes: ["775"],
    policyKey: "financial-instruments",
  },
  {
    key: "other-gains-losses",
    title: "Other gains and losses",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 660,
    supportsSplit: true,
    linkedMappingPrefixes: ["780", "781", "785"],
    policyKey: "operating-expenses",
  },
  {
    key: "taxation",
    title: "Taxation",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 670,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["795"],
    policyKey: "taxation",
  },
  {
    key: "other-comprehensive-income",
    title: "Other comprehensive income",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 680,
    supportsSplit: true,
    linkedMappingPrefixes: ["797"],
    policyKey: "equity",
  },
  {
    key: "discontinued-operations",
    title: "Discontinued operations",
    type: "note",
    statementArea: "soci",
    defaultEnabled: false,
    displayOrder: 690,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["799"],
    policyKey: "discontinued-operations",
  },

  // ---------------------------------------------------------------------------
  // OTHER REQUIRED / SUPPORTING NOTE FAMILIES
  // ---------------------------------------------------------------------------
  {
    key: "cash-generated-from-operations",
    title: "Cash generated from / (used in) operations",
    type: "note",
    statementArea: "cash-flow",
    defaultEnabled: true,
    displayOrder: 800,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: [],
    policyKey: "cash-flow",
  },
  {
    key: "related-parties",
    title: "Related party disclosures",
    type: "note",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 810,
    supportsSplit: true,
    supportsTerms: true,
    linkedMappingPrefixes: ["340.10", "340.11", "340.12", "340.13", "340.14", "340.20", "340.40", "449.10", "449.30", "547", "548", "630.70"],
    policyKey: "related-parties",
  },
  {
    key: "commitments-and-contingencies",
    title: "Commitments and contingencies",
    type: "note",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 820,
    supportsTerms: true,
    linkedMappingPrefixes: [],
    policyKey: "commitments-and-contingencies",
  },
  {
    key: "events-after-reporting-period",
    title: "Events after the reporting period",
    type: "note",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 830,
    supportsTerms: true,
    linkedMappingPrefixes: [],
    policyKey: "events-after-reporting-period",
  },
  {
    key: "going-concern-disclosure",
    title: "Going concern",
    type: "note",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 840,
    supportsTerms: true,
    linkedMappingPrefixes: [],
    policyKey: "going-concern",
  },
];

export const AFS_ACCOUNTING_POLICY_LIBRARY: AfsDisclosureLibraryItem[] = [
  {
    key: "basis-of-preparation",
    title: "Basis of preparation",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 10,
    isCore: true,
  },
  {
    key: "statement-of-compliance",
    title: "Statement of compliance",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 20,
    isCore: true,
  },
  {
    key: "going-concern",
    title: "Going concern",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 30,
    isCore: true,
  },
  {
    key: "material-accounting-policy-information",
    title: "Significant / material accounting policies",
    type: "policy",
    statementArea: "other",
    defaultEnabled: true,
    displayOrder: 40,
    isCore: true,
  },
  {
    key: "financial-instruments",
    title: "Financial instruments",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 100,
  },
  {
    key: "cash-receivables-and-payables",
    title: "Cash, receivables and payables",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 110,
  },
  {
    key: "inventories",
    title: "Inventories",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 120,
  },
  {
    key: "property-plant-equipment",
    title: "Property, plant and equipment",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 130,
  },
  {
    key: "investment-property",
    title: "Investment property",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 140,
  },
  {
    key: "intangible-assets",
    title: "Intangible assets",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 150,
  },
  {
    key: "goodwill-and-impairment",
    title: "Goodwill and impairment",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 160,
  },
  {
    key: "leases",
    title: "Leases",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 170,
  },
  {
    key: "biological-assets",
    title: "Biological assets",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 180,
  },
  {
    key: "group-and-consolidation",
    title: "Subsidiaries, associates and joint ventures",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 190,
  },
  {
    key: "other-assets",
    title: "Other assets",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 200,
  },
  {
    key: "provisions",
    title: "Provisions",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 210,
  },
  {
    key: "employee-benefits",
    title: "Employee benefits",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 220,
  },
  {
    key: "government-grants",
    title: "Government grants",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 230,
  },
  {
    key: "revenue",
    title: "Revenue",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 240,
  },
  {
    key: "operating-expenses",
    title: "Operating expenses",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 250,
  },
  {
    key: "taxation",
    title: "Taxation",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 260,
  },
  {
    key: "equity",
    title: "Equity",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 270,
  },
  {
    key: "assets-held-for-sale",
    title: "Assets and liabilities held for sale",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 280,
  },
  {
    key: "discontinued-operations",
    title: "Discontinued operations",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 290,
  },
  {
    key: "cash-flow",
    title: "Statement of cash flows",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 300,
  },
  {
    key: "related-parties",
    title: "Related parties",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 310,
  },
  {
    key: "commitments-and-contingencies",
    title: "Commitments and contingencies",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 320,
  },
  {
    key: "events-after-reporting-period",
    title: "Events after the reporting period",
    type: "policy",
    statementArea: "other",
    defaultEnabled: false,
    displayOrder: 330,
  },
];

export function sortDisclosureLibrary<T extends { displayOrder: number; title: string }>(items: T[]) {
  return [...items].sort((a, b) => a.displayOrder - b.displayOrder || a.title.localeCompare(b.title));
}
